site_name: DevNotes
theme:
  name: material
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
google_analytics:
  - 'UA-131031623-2'
  - auto
extra:
  social:
    - type: 'github'
      link: 'https://github.com/preslavrachev'
    - type: 'twitter'
      link: 'https://twitter.com/preslavrachev'
